---
- name: Configure repository
  dnf:
    name: 'https://download1.rpmfusion.org/{{ item }}/fedora/rpmfusion-{{ item }}-release-{{ ansible_distribution_major_version }}.noarch.rpm'
    state: present
  with_items: '{{ rpmfusion_repos }}'

- name: Import GPG key
  rpm_key:
    key: 'https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-{{ item }}-fedora-{{ ansible_distribution_major_version }}'
    state: present
  with_items: '{{ rpmfusion_repos }}'
