---
- name: Configure Google Chrome repository
  copy:
    dest: /etc/yum.repos.d/google-chrome.repo
    content: |
      [google-chrome]
      name=google-chrome - $basearch
      baseurl=http://dl.google.com/linux/chrome/rpm/stable/$basearch
      enabled=1
      gpgcheck=1
      gpgkey=https://dl-ssl.google.com/linux/linux_signing_key.pub

- name: Import GPG key
  rpm_key:
    key: https://dl-ssl.google.com/linux/linux_signing_key.pub
    state: present

- name: Install Google Chrome
  dnf:
    name: google-chrome-stable
    state: present
