---
- name: Configure Slack repository
  copy:
    dest: /etc/yum.repos.d/slack.repo
    content: |
      [slacktechnologies_slack]
      name=slacktechnologies_slack
      baseurl=https://packagecloud.io/slacktechnologies/slack/fedora/21/$basearch
      repo_gpgcheck=1
      gpgcheck=0
      enabled=1
      gpgkey=https://packagecloud.io/slacktechnologies/slack/gpgkey
      sslverify=1
      sslcacert=/etc/pki/tls/certs/ca-bundle.crt
      metadata_expire=300

- name: Import GPG key
  rpm_key:
    key: https://packagecloud.io/slacktechnologies/slack/gpgkey
    state: present

- name: Install Slack
  dnf:
    name: slack
    state: present
